name = "fortran-csv-module"
author = "Jacob Williams"
version = "1.2.0"
license = "BSD-3"
copyright = "Copyright 2017 Jacob Williams"
description = "A modern Fortran library for reading and writing CSV (comma-separated value) files."
categories = ["io"]
keywords = ["csv"]

[library]
source-dir = "src"
